micronaut:
  application:
    name: veiculoService
  server:
    port: 8081

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/veiculo-db`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:admin}

jpa:
  default:
    packages-to-scan:
      - 'br.com.curso.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
